{{groovy}}
def currentUser = xcontext.userReference
if (currentUser == null || currentUser.toString().contains('XWikiGuest')) {
  response.sendRedirect(request.contextPath + '/bin/login/XWiki/XWikiLogin')
  return
}

def formToken = request.getParameter('form_token')
// CSRF disabled: token generated by RenderPanel (fetched via JS) is not valid
// in the direct POST context. Auth + group checks provide protection.
// def csrfOk = services.csrf.isTokenValid(formToken)
// if (!csrfOk) {
//   def backUrl = request.getParameter('returnUrl') ?: '/bin/view/Main/WebHome'
//   response.sendRedirect(backUrl + '?qf_error=Security+token+expired.+Please+try+again.')
//   return
// }

def docRef = request.getParameter('docRef') ?: ''
def holderRef = request.getParameter('holderRef') ?: ''
def returnUrl = request.getParameter('returnUrl') ?: '/bin/view/Main/WebHome'
def pType = request.getParameter('type') ?: ''
def pSection = request.getParameter('section') ?: ''
def pComment = request.getParameter('comment') ?: ''
def pAnchorText = request.getParameter('anchorText') ?: ''
def pAnchorOffset = request.getParameter('anchorOffset') ?: '0'

def validTypes = ['Blocker', 'Suggestion', 'Question']
if (!validTypes.contains(pType)) {
  response.sendRedirect(returnUrl + '?qf_error=' + java.net.URLEncoder.encode('Type is required and must be Blocker, Suggestion, or Question.', 'UTF-8'))
  return
}

def trimmedComment = pComment.trim()
if (trimmedComment.isEmpty()) {
  response.sendRedirect(returnUrl + '?qf_error=' + java.net.URLEncoder.encode('Comment text is required.', 'UTF-8'))
  return
}

def sectionLen = pSection.length()
if (sectionLen > 255) {
  response.sendRedirect(returnUrl + '?qf_error=' + java.net.URLEncoder.encode('Section must be 255 characters or less.', 'UTF-8'))
  return
}

def anchorLen = pAnchorText.length()
if (anchorLen > 500) {
  pAnchorText = pAnchorText.substring(0, 500)
}

def holderDocument = xwiki.getDocument(holderRef)
if (holderDocument.isNew()) {
  holderDocument.setTitle('QualityFlow Comments: ' + docRef)
  holderDocument.setContent('Comments holder page for ' + docRef + '. Do not edit manually.')
}

def classRef = 'QualityFlow.CommentClass'
def newObj = holderDocument.newObject(classRef)

newObj.set('type', pType)
newObj.set('status', 'Open')
newObj.set('section', pSection)
newObj.set('anchorText', pAnchorText)
newObj.set('anchorOffset', pAnchorOffset.isInteger() ? pAnchorOffset.toInteger() : 0)
newObj.set('comment', pComment)
newObj.set('author', currentUser.toString())
newObj.set('date', new Date())
newObj.set('document', docRef)

try {
  holderDocument.save('New ' + pType + ' comment by ' + currentUser.name)
} catch (Exception e) {
  response.sendRedirect(returnUrl + '?qf_error=' + java.net.URLEncoder.encode('Failed to save comment: ' + e.getMessage(), 'UTF-8'))
  return
}

response.sendRedirect(returnUrl + '?qf_success=1')
{{/groovy}}
